function FailTest() {
      Log.Error("The test failed due to some condition.Please check this Test");
 
}